version: 2
jobs:
  test:
    working_directory: ~/odyssey
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
          name: Pull submodule
          command: git submodule init && git submodule update --remote
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run tests
          command: rspec

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
